<?php
$HTML->HTML5(null, 'lang=en')
	->title('Xiphes Dropbox Conflict Merger')
	->viewport()
	->css('./res/css/bootstrap.css')
	->css('./res/css/bootstrap-responsive.css')
	->css('./res/css/style.css')
	->css('./res/css/diff.css')
	->css('./res/css/phpdiffmerge.css')

->close('head')
->s_body()
	->s_div('.container-narrow')
	->s_div('.masterhead')
		->gs_ul('.nav nav-pills pull-right')
			->s_li()
				->a('Home', $HTML->baseUrl)
			->close('li')->s_li()
				->a('List Conflicts', '?page\=listConflicts')
			->close('li')->s_li()
				->a('Log out', '?action\=logout')
		->close('ul')
		->h3('Xiphes Dropbox Conflict Merger', '.muted')
	->close('.masterhead')
	->hr();